In [1]:
import pandas as pd

In [2]:
import pandas as pd
df= pd.read_csv("student_marks.csv")
df["average_marks"]=df.select_dtypes(include=["int"]).mean(axis=1)
df["Total marks"]=df.select_dtypes(include=["int"]).sum(axis=1)
def student_grade(average):
    if average>90:
        return "A+"
    elif average>80:
        return "A"
    elif average>70:
        return "B+"
    elif average>60:
       return "B"
    elif average>50:
       return "c+"
    elif average>40:
        return "C"
    elif average>30:
       return "D+"
    else:
        pass
df["grade"]=df["average_marks"].apply(student_grade)
df

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,average_marks,Total marks,grade
0,John,M,05-04-1988,55,45,56,87,21,52,89,65,58.750,470,c+
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2,65.500,524,B
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74,69.500,556,B
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45,73.250,586,B+
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53,73.375,587,B+
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52,69.500,556,B
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61,62.000,496,B
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87,64.625,517,B
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89,73.375,587,B+
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77,70.750,566,B+

In [ ]:
df.info()     
df=pd.read_csv("student_marks.csv")
df.dropna(inplace=True)    
df


df=pd.read_csv("student_marks.csv")
df.dropna(subset=["name","mark"]) 
df   

 
df=pd.read_csv("student_marks.csv")
df.fillna(0,inplace=True)          
df


df=pd.read_csv("student_marks.csv")
df["c"]=df["Biology"].add(5)
df


df.pow()

df.mode()

df.median()

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,c
0,John,M,05-04-1988,55,45,56,87,21,52,89,65,26
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2,95
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74,100
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45,59
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53,101
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52,60
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61,80
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87,30
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89,83
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77,63

In [1]:
# import pandas as pd 
# data1={
#     "age":[1,2,3,4,5],
#     "Name":["anju","akhil","akash","rahul","sanju"]
# }
# data2={
#      "number":[1,2,3,4,5],
#     "nma":["anju","akhil","akash","rahul","sanju"]
# }
# df1=pd.DataFrame(data1)
# df2=pd.DataFrame(data2)
# newdf=pd.concat([df1,df2],ignore_index=True)
# newdf


# import pandas as pd 
# data1={
#     "id":[11,12,13,14],
#     "ages":[10,21,93,34,],
#     "Names":["anju","akhil","akash","rahul"]
# }
# data2={
#      "id":[11,12,13,14],
#      "number":[1,2,3,4],
#     "nma":["anjuzz","Akhil","akash","rahul"]
# }
# df1=pd.DataFrame(data1)
# df2=pd.DataFrame(data2)
# newdf=pd.merge(df1,df2,on="id")
# newdf




import pandas as pd 
data1={
    "num":[11,12,13,14],
    "ages":[10,21,93,34,],
    "Names":["anju","akhil","akash","rahul"]
}
data2={
     "id":[11,67,90,74],
     "number":[1,2,3,4],
    "nma":["anjuzz","Akhil","akash","sanju"]
}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
newdf=df1.join(df2)
newdf

   num  ages  Names  id  number     nma
0   11    10   anju  11       1  anjuzz
1   12    21  akhil  67       2   Akhil
2   13    93  akash  90       3   akash
3   14    34  rahul  74       4   sanju

In [ ]:
import pandas as pd
df=pd.read_csv("student_marks.csv")
df.columns

df=pd.read_csv("student_marks.csv")
df.axes

df=pd.read_csv("student_marks.csv")
df.values

df=pd.read_csv("student_marks.csv")
df.shape

df=pd.read_csv("student_marks.csv")
df.describe

df=pd.read_csv("student_marks.csv")
x={"Unnamed: 0":"student Name"}
df.rename(columns=x,inplace=True)
df
df.at[1,"average_marks"]

,student Name,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77

In [ ]:
import pandas as pd
data1={
    "name":["akash","akhil","anju","akhila"],
    "ages":[10,21,93,34]
}
df=pd.DataFrame(data1)
df.at[1,"ages"]

np.int64(21)

In [4]:
import pandas as pd
chipo=pd.read_csv("student_marks.csv")
chipo.columns

Index(['Unnamed: 0', 'Gender', 'DOB', 'Maths', 'Physics', 'Chemistry',
       'English', 'Biology', 'Economics', 'History', 'Civics'],
      dtype='object')

In [25]:
def calculator_total(df):
    return df["english"]*2
df=pd.DataFrame({
    'maths':[10,21,93,34],
    'malayalam':[10,21,93,34],
    'english':[10,21,93,34]
})
df.apply(calculator_total,axis=1)

def calculator_total(x):
    return x.upper()
df=pd.DataFrame({
    'maths':['sanju','akash','anju','akhil'],
    'malayalam':['rahul','rahul','gokul','jipin'],
    'english':['scammer','drake','wizard','senester']
})
df.applymap(calculator_total)

C:\Users\AKASH\AppData\Local\Temp\ipykernel_21848\1831306112.py:17: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(calculator_total)

   maths malayalam   english
0  SANJU     RAHUL   SCAMMER
1  AKASH     RAHUL     DRAKE
2   ANJU     GOKUL    WIZARD
3  AKHIL     JIPIN  SENESTER

In [ ]:
import pandas as pd
df=pd.DataFrame({
    'maths':[10,21,93,34],
    'malayalam':[10,21,93,34],
    'english':[10,21,93,34]
})
df.insert(0,'physics',['10','21','32','43'])
df
dd=df.assign(chemistry=['10','21','32','43'])
dd
df.drop("malayalam",axis=1)
df.loc[3]
df.replace(10,21)
df.take([2,3])

  physics  maths  malayalam  english
0      10     21         21       21
1      21     21         21       21
2      32     93         93       93
3      43     34         34       34

In [50]:
import pandas as pd
df=pd.read_csv("student_marks.csv")
# df.filter(items=["English","Maths"])
# df
df.get(["malayalam","maths"])

In [3]:
import pandas as pd
df=pd.read_csv("student_marks.csv")
df

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77

In [7]:
user=pd.read_csv("student_marks.csv")
user["Maths"].mean()

np.float64(59.6)